-- 1. Create PROFILES table
CREATE TABLE profiles (
  id TEXT PRIMARY KEY,
  email TEXT,
  password TEXT,
  practice_name TEXT,
  owner_name TEXT,
  phone TEXT,
  role TEXT,
  vapi_assistant_id TEXT,
  display_name TEXT,
  onboarded_at TIMESTAMP WITH TIME ZONE,
  last_payment_at TIMESTAMP WITH TIME ZONE,
  internal_notes TEXT,
  crm_status TEXT,
  last_contacted_at TIMESTAMP WITH TIME ZONE,
  permissions JSONB,
  google_sheet_url TEXT,
  avg_client_value TEXT DEFAULT '350'
);

-- 2. Create CALL_OVERRIDES table
CREATE TABLE call_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assistant_id TEXT NOT NULL,
  call_id TEXT NOT NULL,
  type TEXT NOT NULL, -- 'delete' or 'sentiment'
  value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(assistant_id, call_id, type)
);

-- 3. Create SYSTEM_CONFIG table
CREATE TABLE system_config (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- 4. PERMISSIONS SETUP (Critical for Browser Access)
-- This disables the security blocks that require a Secret Key
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE call_overrides DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_config DISABLE ROW LEVEL SECURITY;

-- This allows your dashboard to talk to the database using your Anon Key
GRANT ALL ON TABLE profiles TO anon, authenticated, postgres, service_role;
GRANT ALL ON TABLE call_overrides TO anon, authenticated, postgres, service_role;
GRANT ALL ON TABLE system_config TO anon, authenticated, postgres, service_role;

-- 5. Create LEADS table (inbound prospects from landing page)
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  source TEXT DEFAULT 'landing_page',
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE leads TO anon, authenticated, postgres, service_role;
GRANT USAGE, SELECT ON SEQUENCE leads_id_seq TO anon, authenticated, postgres, service_role;
